[tool.black]
line-length = 99
exclude = '(venv|migrations|.pytest_cache|.mypy_cache)'

[tool.isort]
line_length = 99
skip = 'venv,migrations,.pytest_cache,.mypy_cache'
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true
use_parentheses = true
